apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argroj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ariefshaik7/llm-inference.git'
    path: 'helm/llm-api-chart'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true