apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "YourSuperSecretAndStrongPassword123" 
  POSTGRES_DB: "llm_usage_db"