apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-api-sa
  namespace: {{.Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader-role
  namespace: {{.Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["postgres-secret"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llm-api-secret-access
  namespace: {{.Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: llm-api-sa
  namespace: {{.Release.Namespace }}
roleRef:
  kind: Role
  name: secret-reader-role
  apiGroup: rbac.authorization.k8s.io