apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-api-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["postgres-secret"] 
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llm-api-secret-access
subjects:
- kind: ServiceAccount
  name: llm-api-sa
roleRef:
  kind: Role
  name: secret-reader-role
  apiGroup: rbac.authorization.k8s.io