apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-api-monitor
  namespace: {{.Release.Namespace }}
  labels:
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: llm-api
  namespaceSelector:
    matchNames:
      - {{.Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s