apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-api-monitor
  namespace: default
  labels:
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: llm-api
  namespaceSelector:
    matchNames:
      - default
      - llm-inference
  endpoints:
    - port: http           
      path: /metrics
      interval: 15s
