apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api-deployment
  labels:
    app: llm-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-api
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      serviceAccountName: llm-api-sa
      nodeSelector:
        gpu: "true"
      containers:
      - name: llm-api
        image: ariefshaik007/llm-api:17817944529
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: "postgres-svc"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret 
              key: POSTGRES_DB   
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:  
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          requests:
            cpu: "250m" 
          limits:
            cpu: "500m" 